name: yu_ngantri_medic_user
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  provider: ^4.1.3
  flutter_spinkit: ^4.1.2+1
  firebase_messaging: ^6.0.16
  fluttertoast: ^4.0.0
  flutter_datetime_picker: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-Light.ttf
          weight: 300
